# Generated by Django 3.2.5 on 2023-08-22 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='0x', max_length=42)),
                ('name', models.CharField(default='ERC20', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('chainid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='0x', max_length=42)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('project_address', models.CharField(max_length=42)),
                ('community_oversight', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('release_epoch', models.IntegerField()),
                ('creation_hash', models.CharField(default='0x', max_length=66)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fundoorAPI.category')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fundoorAPI.currency')),
                ('fundraiser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fundoorAPI.user')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fundoorAPI.status')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='user_upload/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fundoorAPI.project')),
            ],
        ),
        migrations.AddField(
            model_name='currency',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fundoorAPI.network'),
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('usd_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=80)),
                ('hsh', models.CharField(default='0x', max_length=100)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fundoorAPI.currency')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fundoorAPI.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fundoorAPI.user')),
            ],
        ),
        migrations.CreateModel(
            name='CommunityProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('title', models.CharField(max_length=100)),
                ('onchain_proposal_nonce', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fundoorAPI.project')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fundoorAPI.status')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fundoorAPI.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fundoorAPI.user')),
            ],
        ),
    ]
