# Generated by Django 3.2.5 on 2023-08-23 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundoorAPI', '0002_auto_20230822_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
