# Generated by Django 3.2.5 on 2023-08-30 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fundoorAPI', '0005_auto_20230826_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityproposal',
            name='created_at',
        ),
        migrations.AddField(
            model_name='communityproposal',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fundoorAPI.currency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='communityproposal',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
    ]
