# Generated by Django 3.2.5 on 2023-08-30 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundoorAPI', '0006_auto_20230830_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityproposal',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='communityproposal',
            name='deadline',
        ),
    ]
