# Generated by Django 3.2.5 on 2023-09-02 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fundoorAPI', '0007_auto_20230830_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=18, max_digits=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vote', models.BooleanField()),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fundoorAPI.communityproposal')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fundoorAPI.user')),
            ],
        ),
    ]
