# Generated by Django 3.2.5 on 2023-09-02 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundoorAPI', '0008_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityproposal',
            name='status',
        ),
    ]
