# Generated by Django 3.2.5 on 2023-09-03 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundoorAPI', '0009_remove_communityproposal_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
