# Generated by Django 3.2.5 on 2023-09-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundoorAPI', '0010_auto_20230903_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_hero',
            field=models.BooleanField(default=False),
        ),
    ]
