# Generated by Django 3.2.5 on 2023-09-10 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundoorAPI', '0011_project_is_hero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_hero',
        ),
    ]
